#!/bin/bash

## 
#
# Title:        Screenshot
# Description:  The purpose of this file is to provide a simple screenshot mechanism.
# Author:       github.com/andersro93
# 
##

# Some readonly constants
MODE_SELECTION="selection"
MODE_WINDOW="window"

# Detect what mode to use
if [[ $# -eq 0 ]]; then
    
    # Take screenshot of entire screen(s)
    maim -m 10 --format png /dev/stdout | xclip -selection clipboard -t image/png -i

elif [[ $1 -eq "$MODE_SELECTION" ]]; then

    # Take screenshot of the selected area
    maim -s -m 10 --format png /dev/stdout | xclip -selection clipboard -t image/png -i

elif [[ $1 -eq "$MODE_WINDOW" ]]; then

    # Take screenshot of the current window
    maim -i -m 10 --format png /dev/stdout | xclip -selection clipboard -t image/png -i
else

    echo "Error: unknown mode was specified"
fi

# Send notification after all is done
notify-send 'Printscreen' 'Screenshot saved to clipboard' -u low -t 2000

